### ISSUE TITLE
ValidationError: x is not a multiple of 1e-10

### ISSUE THREAD

**Issue by robindebois** [singer-io/tap-mambu#8]
I'm running the mambu-tap hooked up to my mambu dev environment and I'm piping it into either `target-csv` or `target-json` (just for testing purposes). I'm running it as:

```
.tap/bin/tap-mambu --config config.json --catalog catalog.json | .target/bin/target-json
```
It's throwing me the following error:
```
Traceback (most recent call last):
  File ".target/bin/target-json", line 11, in <module>
    load_entry_point('target-json==0.0.11', 'console_scripts', 'target-json')()
  File "/Users/<REDACTED>/Projects/tap/.target/lib/python3.7/site-packages/target_json.py", line 126, in main
    config.get('bookmark_keys', {}))
  File "/Users/<REDACTED>/Projects/tap/.target/lib/python3.7/site-packages/target_json.py", line 50, in persist_lines
    validators[o['stream']].validate(o['record'])
  File "/Users/<REDACTED>/Projects/tap/.target/lib/python3.7/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
jsonschema.exceptions.ValidationError: 0.09 is not a multiple of 1e-10

Failed validating 'multipleOf' in schema['properties']['accrued_interest']:
    {'multipleOf': 1e-10, 'type': ['null', 'number']}

On instance['accrued_interest']:
    0.09
```

This seems quite a common issue reported in the jsonschema library... https://github.com/Julian/jsonschema/issues/247

I had to work around it by removing all these validations from the catalog.json which seems undesirable. Any better suggestions? 

For reference, it goes wrong on the target (I presume), and this is the configuration:

```
backoff==1.3.2
certifi==2020.4.5.1
chardet==3.0.4
idna==2.7
jsonschema==2.6.0
pendulum==1.2.0
python-dateutil==2.8.1
pytz==2019.3
pytzdata==2019.3
requests==2.20.0
simplejson==3.11.1
singer-python==5.0.4
six==1.14.0
tap-fixerio==0.1.3
target-csv==0.3.0
target-json==0.0.11
tzlocal==2.0.0
urllib3==1.24.3
```

**Comment by jeffhuth-bytecode** [comment]
Unfortunately, `target-json` has not been updated in a while and does not support JSON schemas with `multipleOf` parameters for numbers. This parameter helps database targets determine the data type decimal digits needed. I think this issue should be logged against the `target-json` repository: https://github.com/dvelardez/target-json
This is a 3rd party target maintained/owned by another developer.

**Comment by robindebois** [comment]
Hey Jeff, 
You're absolutely right.. my mistake. Let me close it and have a look at the targets.
